# Generated by Django 4.2.6 on 2023-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
