# Generated by Django 4.2.6 on 2024-01-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0002_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('color_code', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_C', to='ShopManageMent.color')),
                ('count_inventory', models.ManyToManyField(related_name='inventory_count', to='ShopManageMent.countinventory')),
            ],
        ),
        migrations.AddField(
            model_name='countinventory',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countinventory_S', to='ShopManageMent.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ManyToManyField(related_name='product', to='ShopManageMent.inventory'),
        ),
    ]
