# Generated by Django 4.2.6 on 2024-01-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0003_color_countinventory_size_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.ManyToManyField(related_name='product_inv', to='ShopManageMent.inventory'),
        ),
        migrations.CreateModel(
            name='CategoryTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('category_three', models.ManyToManyField(related_name='cat_2', to='ShopManageMent.categorythree')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('category_two', models.ManyToManyField(related_name='cat_1', to='ShopManageMent.categorytwo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='ShopManageMent.categoryone'),
        ),
    ]
