# Generated by Django 4.2.6 on 2024-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0004_categorythree_alter_product_inventory_categorytwo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('dis', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.ManyToManyField(related_name='product_property', to='ShopManageMent.propery'),
        ),
    ]
