# Generated by Django 4.2.6 on 2024-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0005_propery_product_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciFication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('dis', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(related_name='product_specification', to='ShopManageMent.specification'),
        ),
    ]
