# Generated by Django 4.2.6 on 2024-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0008_abutus_howtobuy_qustion_returnterms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
