# Generated by Django 4.2.6 on 2024-05-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0010_alter_abutus_text_alter_howtobuy_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleQuwtion',
            new_name='TitleQuestion',
        ),
    ]
