# Generated by Django 4.2.6 on 2024-02-14 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InstallMent', '0045_order_marsole_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_active', models.CharField(choices=[('wholesaler', 'WHOLESALER'), ('store', 'STORE'), ('free sale', 'FREE SALE')], default='wholesaler', max_length=50)),
                ('store_type', models.CharField(choices=[('ارزانسرا', 'ارزانسرا'), ('بوتیک', 'بوتیک'), ('حراجی', 'حراجی')], max_length=50)),
                ('store_address', models.TextField(null=True)),
                ('city_whole_saler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InstallMent.city')),
                ('state_whole_saler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InstallMent.state')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('dis', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Networker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('child', 'CHILD'), ('dosen matter', 'DOSEN MATTER')], max_length=50)),
                ('social_media_status', models.BooleanField(default=False)),
                ('rubika_id', models.CharField(max_length=50, null=True)),
                ('telegram_id', models.CharField(max_length=50, null=True)),
                ('instagram_id', models.CharField(max_length=50, null=True)),
                ('poz_machine_status', models.CharField(choices=[('i have', 'I HAVE'), ('i dont have', 'I DONT HAVE'), ('some one else', 'SOME ONE ELSE')], max_length=50)),
                ('poz_machine_owner_fullname', models.CharField(max_length=50, null=True)),
                ('is_representative', models.BooleanField(default=False)),
                ('representative', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='NetworkerPanel.representative')),
                ('type_of_activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='NetworkerPanel.activitytype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_networker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
