# Generated by Django 4.2.6 on 2024-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkerPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networker',
            name='phone_vrify_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='networker',
            name='phone_vrify_status',
            field=models.BooleanField(default=False),
        ),
    ]
