# Generated by Django 4.2.6 on 2024-03-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0045_order_marsole_code'),
        ('NetworkerPanel', '0002_networker_phone_vrify_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('meli_code', models.CharField(max_length=200, null=True)),
                ('house_number', models.CharField(max_length=200, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstallMent.city')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstallMent.state')),
            ],
        ),
        migrations.AddField(
            model_name='networker',
            name='addres',
            field=models.ManyToManyField(to='NetworkerPanel.addres'),
        ),
    ]
