# Generated by Django 4.2.6 on 2024-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkerPanel', '0003_addres_networker_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='addres',
            name='main_addres',
            field=models.TextField(null=True),
        ),
    ]
