"""
Django settings for Ib7Main project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j35ye9xre@x$7_wvyd^-5+-o!fnddihwvln5n_amphts-si^(*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ib7.ir','0.0.0.0','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'InstallMent',
    'persian_date',
    'HomePage',
    'UserManageMent',
    'ShopManageMent',
    'NetworkerPanel',
    'Shop',
    'ckeditor',
    'django_cleanup.apps.CleanupConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Ib7Main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
 		'Shop.context_processors.custom_context',
            ],
        },
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:*",  # Add your frontend URL here
    "http://localhost:800",  # Add your frontend URL here
    "https://ib7.ir",  # Add your production domain here
    "https://jmwear.ir",  # Add your production domain here
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
# Allow all headers for now, adjust as needed
CORS_ALLOW_ALL_HEADERS = True
ROOT_URLCONF = 'Ib7Main.urls'
WSGI_APPLICATION = 'Ib7Main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ib7main_db',
        'USER': 'neon',
        'PASSWORD': 'Amin09388148998@',
        'HOST': 'localhost',
        'PORT': 5432,
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # Other authentication classes...
    ],
    # Other settings...
}

# Disable CSRF for the entire project
#CSRF_COOKIE_SECURE = False
#CSRF_COOKIE_SAMESITE = None





AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


import os
STATIC_URL = 'static/'
MEDIA_URL = "/media/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "assets")]
MEDIA_ROOT = "/var/www/api.ib7main.ir/media"
STATIC_ROOT = "/var/www/api.ib7main.ir/static"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
CKEDITOR_UPLOAD_PATH = "uploads/"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'UserManageMent.UserAccount'
CKEDITOR_CONFIGS = {
    'default': {
        'contentsLangDirection': 'rtl',
        'toolbar': 'full',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Image'],
            ['Maximize']
        ],
        'height': 300,
        'width': 800,
        'language': 'fa',  # Specify the language code for Persian
        # Optionally, you can specify the path to the language file if you have it locally
        # 'language': 'your_custom_path/fa.js',
    },
}