# Generated by Django 4.2.3 on 2023-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_image', models.ImageField(null=True, upload_to='image/documents')),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('state', models.IntegerField(null=True)),
                ('city', models.IntegerField(null=True)),
                ('conteract_type', models.CharField(max_length=200, null=True)),
                ('conteract_date', models.CharField(max_length=200, null=True)),
                ('discription', models.TextField(null=True)),
                ('documnent', models.ManyToManyField(to='InstallMent.document')),
            ],
        ),
    ]
