# Generated by Django 4.2.3 on 2023-08-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
