# Generated by Django 4.2.3 on 2023-08-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0003_peymenddate_product_product_factor_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
