# Generated by Django 4.2.3 on 2023-08-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0005_alter_product_numbers_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='InstallMent.product'),
        ),
        migrations.DeleteModel(
            name='Product_Factor',
        ),
    ]
