# Generated by Django 4.2.3 on 2023-08-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0006_alter_order_products_delete_product_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer',
            new_name='prepeyment_date',
        ),
    ]
