# Generated by Django 4.2.3 on 2023-08-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0007_rename_offer_order_prepeyment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='peymenddate',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
