# Generated by Django 4.2.3 on 2023-08-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0008_peymenddate_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dis',
            field=models.TextField(null=True),
        ),
    ]
