# Generated by Django 4.2.3 on 2023-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0010_peymenddate_peyed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='fake_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
