# Generated by Django 4.2.3 on 2023-09-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0011_costumer_fake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fake_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
