# Generated by Django 4.2.6 on 2023-11-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopManageMent', '0002_product_created'),
        ('InstallMent', '0015_costumer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('numbers', models.IntegerField(null=True)),
                ('main_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShopManageMent.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='InstallMent.orderproduct'),
        ),
    ]
