# Generated by Django 4.2.6 on 2023-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0016_orderproduct_delete_product_alter_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_deposited', models.CharField(max_length=200, null=True)),
                ('deposit_date', models.CharField(max_length=80, null=True)),
                ('card_number_origin', models.CharField(max_length=100, null=True)),
                ('card_number_destination', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='deposit',
            field=models.ManyToManyField(to='InstallMent.deposit'),
        ),
    ]
