# Generated by Django 4.2.6 on 2023-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0017_deposit_costumer_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='bestankar_price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
