# Generated by Django 4.2.6 on 2023-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0020_deposit_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='deposit',
            field=models.ManyToManyField(related_name='costumer_deposit', to='InstallMent.deposit'),
        ),
    ]
