# Generated by Django 4.2.6 on 2023-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0021_alter_costumer_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='deposit',
            field=models.ManyToManyField(to='InstallMent.deposit'),
        ),
    ]
