# Generated by Django 4.2.6 on 2023-11-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0022_alter_costumer_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='deposit',
            new_name='depositt',
        ),
    ]
