# Generated by Django 4.2.6 on 2023-11-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0024_alter_costumer_depositt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='depositt',
            field=models.ManyToManyField(related_name='costumer_deposit', to='InstallMent.deposit'),
        ),
    ]
