# Generated by Django 4.2.6 on 2023-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0025_alter_costumer_depositt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='depositt',
        ),
        migrations.AddField(
            model_name='costumer',
            name='deposits',
            field=models.ManyToManyField(to='InstallMent.deposit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_pro', to='InstallMent.orderproduct'),
        ),
    ]
