# Generated by Django 4.2.6 on 2023-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0026_remove_costumer_depositt_costumer_deposits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='deposits',
            field=models.ManyToManyField(related_name='dep_costu', to='InstallMent.deposit'),
        ),
    ]
