# Generated by Django 4.2.6 on 2023-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0028_deposit_fake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to='images/factor_images/'),
        ),
    ]
