# Generated by Django 4.2.6 on 2023-12-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0030_order_peyment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChashPeyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_receiver', models.IntegerField(null=True)),
                ('card_numer_origin', models.CharField(max_length=200, null=True)),
                ('card_name_origin', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPeyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='images/check_images/')),
                ('check_owner', models.CharField(max_length=50, null=True)),
                ('dead_time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cash_peyment_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstallMent.chashpeyment'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_peyment_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstallMent.checkpeyment'),
        ),
    ]
