# Generated by Django 4.2.6 on 2023-12-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0031_chashpeyment_checkpeyment_order_cash_peyment_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='peyment_type',
            field=models.CharField(choices=[('نقد', 'نقد'), ('اقساط', 'اقساط'), ('چک', 'چک'), ('نسیه', 'نسیه')], max_length=20, null=True),
        ),
    ]
