# Generated by Django 4.2.6 on 2023-12-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0033_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chashpeyment',
            name='destination_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chashpeyment',
            name='money_recaiver_ib7',
            field=models.IntegerField(null=True),
        ),
    ]
