# Generated by Django 4.2.6 on 2023-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0034_chashpeyment_destination_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpeyment',
            name='prepeyment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
