# Generated by Django 4.2.6 on 2023-12-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0035_checkpeyment_prepeyment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chashpeyment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkpeyment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
