# Generated by Django 4.2.6 on 2023-12-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0036_chashpeyment_discount_checkpeyment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpeyment',
            name='check_recaiver',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
