# Generated by Django 4.2.6 on 2023-12-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0037_checkpeyment_check_recaiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpeyment',
            name='discount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkpeyment',
            name='prepeyment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
