# Generated by Django 4.2.6 on 2023-12-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0038_alter_checkpeyment_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpeyment',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
