# Generated by Django 4.2.6 on 2023-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0039_alter_checkpeyment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='moeny_recaiver_ib7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='money_recaiver_jmwear',
            field=models.IntegerField(null=True),
        ),
    ]
