# Generated by Django 4.2.6 on 2023-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0040_deposit_moeny_recaiver_ib7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='money_recaive_type',
            field=models.BooleanField(default=False),
        ),
    ]
