# Generated by Django 4.2.6 on 2023-12-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0041_deposit_money_recaive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='check_peyment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstallMent.checkpeyment'),
        ),
    ]
