# Generated by Django 4.2.6 on 2023-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0043_deposit_peyment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSmsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('پست', 'پست'), ('تیپاکس', 'تیپاکس'), ('باربری', 'باربری')], default='پست', max_length=50)),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('marsole_code', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('fake_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
