# Generated by Django 4.2.6 on 2023-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstallMent', '0044_postsmsmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marsole_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
