# Generated by Django 4.2.6 on 2023-10-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManageMent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPermissionn',
        ),
    ]
