# Generated by Django 4.2.6 on 2023-11-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManageMent', '0002_delete_grouppermissionn'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissionn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, null=True)),
                ('read', models.JSONField(null=True)),
                ('create', models.JSONField(null=True)),
                ('delete', models.JSONField(null=True)),
                ('edit', models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cloth_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cloth_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cloth_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tailor_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tailor_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tailor_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tailor_read',
            field=models.BooleanField(default=False),
        ),
    ]
